sudo: required
dist: precise

language: php
php:
  - 5.6
  - 7

before_install:
  - sh contrib/travis-elasticsearch.sh
  - sudo service elasticsearch start

install:
  - composer install --dev

script: ./bin/phpunit --coverage-text

notifications:
  email: false
